fixed
nao1215/mimixbox pull request #88
Opened 2022-06-22 09:13 UTC by k-avy

2022-06-22 13:24 UTC, nao1215 requested changes
You have made some great additions.
I would like to ask you to correct a few things. I am giving you a suggestion.

There is a missing spec file for testing, but I assume that this is not a problem here.

2022-06-22 13:24 UTC, nao1215 commented on internal/applets/shellutils/printf/printf.go
> +}
```suggestion
const cmdName string = "printf"
const version = "1.0.0"

var osExit = os.Exit

type options struct {
	Version bool `short:"v" long:"version" description:"Show printf command version"`
}
```

2022-06-22 13:34 UTC, nao1215 commented
If you intend to add test code, please work through the steps below.
1.  Add test/it/spec/printf_spec.sh
2. Add test code at test/it/spec/printf_spec.sh
3. Run integration test.
```
$ cd <project root>
$ make it

(in docker)
$ $ ./do_integration_test.sh 
```

2022-06-22 13:50 UTC, nao1215 commented
@k-avy 
After the GitHub Actions error (Build, Integration Test) is fixed, I will merge this PR.

2022-06-23 05:56 UTC, k-avy commented
Thank you for reviewing i will fix the error and push it again.

2022-06-23 07:05 UTC, k-avy commented
I have fixed the error and removed the test for now as i dont know how to do that.

2022-06-23 13:22 UTC, nao1215 commented
@k-avy 
You have done a very good job.
I will merge your pr.

2022-06-23 13:22 UTC, merged

2022-06-23 13:51 UTC, k-avy commented
@nao1215 
Thank you for the appreciation.